version: '3'

services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/DockerFile
    ports: 
    - 80:80
  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes: 
      - ./postgres:/var/lib/postgres/data
    ports: 
      - 5432
  app:
    build: .
    volumes: 
      - ./rails_app:/rails_app
    ports: 
      - 3000:3000
    environment: 
      - RAILS_ENV=${RAILS_ENV}
    depends_on: 
      - db
